### ISSUE TITLE
react-native-reanimated v2

### ISSUE THREAD

**Issue by prabhatm6** [gorhom/react-native-paper-onboarding#30]
this library is awesome but not working because reanimated library is depracted

**Comment by gorhom** [comment]
@prabhatm6 this should work with `v2`,  but if not , i'll work on compatibility later 👍

**Comment by jonathanmv** [comment]
I second @prabhatm6. I'm using `v2` and it breaks when [calling the interpolate](https://github.com/gorhom/react-native-paper-onboarding/blob/master/src/useTiming.ts#L58) function on useTiming.ts.

The `Animated.interpolate` function receives 3 or 4 params in `v2` instead of 2.
In their migration documentation they suggest to use the function `interpolateNode` because the `interpolate` function was [renamed](https://docs.swmansion.com/react-native-reanimated/docs/migration#1-interpolate-renamed-to-interpolatenode)

**Comment by aleppos** [comment]
any update?

**Comment by gorhom** [comment]
this should be resolved with `v1.1.0` 👍
